### ISSUE TITLE
npm install of package not working in svelte project

### ISSUE THREAD

**Issue by dirk-bester** [stefnotch/json-safe-stringify#1]
Unfortunately I am newly new to Javascript after a 7 year absence. I don't know anything about packages yet and comparing your package declarations to others reveals a bewildering diversity and no obvious lucky hack.

npm install json-safe-stringify
did update my package.json
`  "dependencies": {
    "bootstrap": "^5.2.3",
    "json-safe-stringify": "^1.0.3",
    "svelte-local-storage-store": "^0.4.0",
    "sveltestrap": "^5.10.0"
  }
`
However
`import {
	jsonParseReviver,
	JsonSerializer,
	jsonStringifyReplacer,
} from "json-safe-stringify";`
Yields error:
Cannot find module 'json-safe-stringify' or its corresponding type declarations.ts(2307)

I am unclear on the fix. Are there 5 million different packaging systems each with its own magic variables and this is missing it for my exact combo of frameworks?

**Comment by stefnotch** [comment]
How did you create your svelte project, so that I can reproduce this?

(Or do you have a minimal sample where I can try this out?)

**Comment by stefnotch** [comment]
Okay, I took a look at this. Based on the error message, it's Typescript that is unable to find the library.

Apparently, that is because I figured that using the latest features would be the easiest thing to do. After all, Javascript's importing stuff has changed a lot over the years and is a bit messy at the moment. (It's slowly getting better, with more and more libraries switching to the newer and hopefully better designed ES Modules standard.)

So I used the [`"export"` field in the `package.json`](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing). *But*, Typescript doesn't read that, until you tell it to.

To tell Typescript that it should start to use the new features as well, you'll have to go to your `tsconfig.json`, or create one if there is none, and make sure that `"module": "nodenext", ` is in there.
e.g.
```json
{
    "compilerOptions": {
        /* This tells Typescript that we're working with the new importing mechanisms */
        "module": "nodenext", 
    }
}
```
And then you can read [the documentation](https://www.typescriptlang.org/docs/handbook/esm-node.html) for what that means. One thing that you *might* notice is that all the relative imports in your code need a file extension. Like `import { cat } from "./cat.ts"`

**Comment by stefnotch** [comment]
If that causes you more problems than it's worth, I'll offer you two lovely alternatives
1. You may copy-paste my code straight into your project, either with the license, or I can relicense it under CC0.
2. I could bite the bullet and add in some older[1] stuff to the `package.json` so that it'll probably work with your toolchain.



[1] Where older apparently means *not very old at all, but web development likes changing things very often*.

**Comment by dirk-bester** [comment]
The inability to serialize a built in type is pretty lame, but json is already date stupid so whatever. The last time I wrote this exact code was 10 years ago at SGI. Needed set, date and time handling iirc plus some more stuff because machine learning in C++ on the server. Although I used a switch statement and specifically stripped anything not POJsO.

JSON (2001) is long out of patent range. I am OK rolling the dice. I will link to your github in the copy paste and add the CC0 comment from stack.

**Comment by dirk-bester** [comment]
For posterity the reproduction:
`npm create vite@latest
npm install

npm install sveltestrap svelte
npm install bootstrap
npm install svelte-local-storage-store
npm install json-safe-stringify
npm install

npm run dev
`
I think that svelte-local-storage-store is your competition. They claim to handle localStorage across sessions and tabs. Made me feel lazy though.

Also thank you for the effort!

**Comment by stefnotch** [comment]
Lovely, thank you for the reproduction. Glad to hear that the CC0 licensing option took care of it, after all this is code that I put online to spare other people the trouble. :)

**Comment by dirk-bester** [comment]
Final info: I eventually settled on https://github.com/samchon/typia for Typescript based I/O.
